# Generated by Django 4.2.6 on 2023-10-08 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200, null=True)),
                ('job_title', models.TextField()),
                ('linkedin_url', models.URLField()),
                ('image_url', models.URLField()),
                ('bio', models.TextField()),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('owner', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, null=True)),
                ('location_slug', models.SlugField(unique=True)),
            ],
        ),
    ]
