# Generated by Django 4.2.3 on 2023-10-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='herprofile',
            name='skills',
            field=models.ManyToManyField(null=True, to='her_profiles.skills'),
        ),
    ]
