# Generated by Django 4.2.6 on 2023-10-08 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herprofile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='her_profiles.location'),
        ),
    ]
