# Generated by Django 4.2.3 on 2023-10-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0002_remove_herprofile_skills_herprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herprofile',
            name='skills',
            field=models.ManyToManyField(to='her_profiles.skills'),
        ),
    ]
