# Generated by Django 4.2.3 on 2023-10-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0003_alter_herprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herprofile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_herprofiles', to='her_profiles.location'),
        ),
        migrations.RemoveField(
            model_name='herprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='herprofile',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
