# Generated by Django 4.2.6 on 2023-10-16 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('her_profiles', '0003_alter_herprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herprofile',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_profiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
