# Generated by Django 4.2.3 on 2023-10-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0004_alter_herprofile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_slug',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_slug',
        ),
    ]
