# Generated by Django 4.2.3 on 2023-10-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0004_alter_herprofile_location_remove_herprofile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herprofile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='her_profiles.location'),
        ),
    ]
