# Generated by Django 4.2.3 on 2023-10-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0005_alter_herprofile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
