# Generated by Django 4.2.3 on 2023-10-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0006_delete_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_slug',
        ),
    ]
