# Generated by Django 4.2.3 on 2023-10-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0007_remove_location_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herprofile',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
