# Generated by Django 4.2.3 on 2023-10-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0009_location_alter_herprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='herprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='herprofile',
            name='skills',
            field=models.ManyToManyField(to='her_profiles.skills'),
        ),
    ]
