# Generated by Django 4.2.3 on 2023-10-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0010_skills_remove_herprofile_skills_herprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
