# Generated by Django 4.2.3 on 2023-10-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_profiles', '0011_skills_skill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
